### ISSUE TITLE
The comments of functions are same

### ISSUE THREAD

**Issue by berkanttubi** [liorsidi/StockSimilarity#4]
In similarity_functions.py, the comments of ;
```python
def fix_stock_len(stock1, stock2):
def correlate_stock_len(stock1, stock2):
def correlate_stock_len_delay(stock1, stock2, delay=1): 
```
are the same... How can i learn more about this functions ? Can you help me please?

**Comment by liorsidi** [comment]
@berkanttubi You are right, just fixed with new notes
